name: PROD CI
on:
  push:
    branches:
      - main
      - dev
jobs:
  main:
    name: PROD pipeline
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
